

services:
  mongo:
    image: mongo
    container_name: callcenter_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: callcenter_redis
    ports:
      - "6379:6379"


  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: callcenter_backend
    ports:
      - "5001:5000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/callcenter

volumes:
  mongo_data:

